### ISSUE TITLE
Set up metric or Imperial - UIKit

### ISSUE THREAD

**Issue by matthewfernst** [matthewfernst/Mountain-UI-Companion-App#29]
Provide users with options for selecting their preferred units

**Comment by mrrosoff** [comment]
This is supported for all fields that it makes sense to convert between on the backend. Please see schema for details.

**Comment by matthewfernst** [comment]
It was found by Beta Tester Megan that the slope files are saved in metric units. Maybe for now switch the setting to metric in app and enable later.
